### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mathieuboudreau** [neurolibre/docs.neurolibre.org#14]
The docs (https://docs.neurolibre.com) used to work, but now show a 403 error. 

Is this a known/expected behaviour at the moment? I can't recall; did we migrate from org to com or com to org?

**Comment by pbellec** [comment]
mmmhh not it is not expected. 

We did migrate from com to org.

I am not sure what's going on, will check.

**Comment by mathieuboudreau** [comment]
Perfect, thanks! I had clicked on the link shared in our Slack, it must have been just before the migration
