### ISSUE TITLE
Review: pip resolver note

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/docs.neurolibre.org#18]
I accidentally pushed into master without asking for a review.
@mathieuboudreau don't you mind looking at this commit since you are currently facing this issue?

https://github.com/neurolibre/docs.neurolibre.org/commit/c0c155dc1dd5e0ec84bc1122e75f96f2bb0d3a5b

**Comment by mathieuboudreau** [comment]
Looks good to me!
