### ISSUE TITLE
Update submission docs to note force-execute

### ISSUE THREAD

**Issue by pbellec** [neurolibre/docs.neurolibre.org#22]
I am testing the T1 book freshly generated by roboneuro. 
If I use the binder link on the following page, the server starts alright, but none of the cells execute properly
http://neurolibre-data.conp.cloud/book-artifacts/qmrlab/github.com/t1_book/90dc33047e911cc598237621df1e3eebc3207ce0/_build/html/01/IR_DataFitting.html

**Comment by ltetrel** [comment]
https://github.com/neurolibre/docs.neurolibre.org/commit/5491568a8e300a7a772942d56fdde9172e535e24
