### ISSUE TITLE
document data limits 

### ISSUE THREAD

**Issue by pbellec** [neurolibre/docs.neurolibre.org#26]
and encourage pulling from stable sources (inc DOIs).

**Comment by ltetrel** [comment]
About user storage, i finally found that binderhub (or rather jupyterhub) allocate 10GB per user by default.
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-storage.html

For the dataset storage we agreed on few GB.

**Comment by ltetrel** [comment]
For what data is acessible or not, we could use cookiecutter data layout proposal 
https://github.com/drivendata/cookiecutter-data-science/tree/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/data

`REPO_ROOT/data/raw` would be read-only, where all neurolibre datasets are stored.
the rest can be user by the user.

**Comment by ltetrel** [comment]
https://github.com/neurolibre/docs.neurolibre.org/commit/65bfb4b081d8689782f9345e2c2adb8c2c80ad23
