### ISSUE TITLE
_config.yml link does not work

### ISSUE THREAD

**Issue by mirhnius** [neurolibre/docs.neurolibre.org#46]
The link for _config.yml documentation in [this page](https://docs.neurolibre.org/en/latest/STRUCTURE.html#the-binder-folder-runtime) does not redirect to the Jupyter Book config documentation. Correct address: https://jupyterbook.org/en/stable/customize/config.html

**Comment by agahkarakuzu** [comment]
Thank you so much @mirhnius ! Just pushed a fix, now the link points to the correct target.
